# Generated by Django 3.0.6 on 2020-05-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_cases', models.IntegerField()),
                ('district', models.TextField()),
                ('zone', models.TextField()),
            ],
        ),
    ]
