# Generated by Django 3.0.6 on 2020-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_auto_20200506_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='DistrictsModel',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
